### ISSUE TITLE
The software is missing

### ISSUE THREAD

**Issue by WildSpirit007** [LiveStockShapeAnalysis/LiveStockShapeAnalysis-Software#1]
Hello,
I read your paper, and it seems very interesting. However, the code is not available though It was mentioned that was freely avalaible
I am looking forward to run the program so I can be able to see the efficiency of the program in terms of the computational time.
Thank you

**Comment by niallomahony93** [comment]
I too would like to evaluate the software.

**Comment by LiveStockShapeAnalysis** [comment]
> Hello,
> I read your paper, and it seems very interesting. However, the code is not available though It was mentioned that was freely avalaible
> I am looking forward to run the program so I can be able to see the efficiency of the program in terms of the computational time.
> Thank you

We do upload the bin file in the release section part. Please check.

**Comment by LiveStockShapeAnalysis** [comment]
> I too would like to evaluate the software.

We do upload the bin file in the release section part. Please check.
